# Generated by Django 3.2.6 on 2021-08-28 20:04

from django.db import migrations, models
import django.db.models.deletion
from django.core.validators import MaxValueValidator, MinValueValidator
import histograma.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Municipio",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("municipio", models.CharField(max_length=100)),
                ("numero_consultas", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Histograma",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("año", models.IntegerField()),
                ("per_capita", models.BooleanField()),
                ("cuantil_inferior", models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(30)])),
                ("cuantil_superior", models.IntegerField(default=95, validators=[MinValueValidator(70), MaxValueValidator(100)])),
                ("tamaño_contenedor", models.IntegerField(default=95, validators=[MinValueValidator(100), MaxValueValidator(5000)])),
                ("svg_histograma", models.TextField()),
                ("municipio", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="histograma.municipio")),
            ],
        ),
    ]
